#!/bin/sh

set -e
EMAIL=${EMAIL:=aaa@bbb.com}
TOKEN=${TOKEN:=aaabbbcccdddeeefff}
DOMAIN=${DOMAIN:=aaabbbccc.moe}
HEADER=${HEADER:=header}
TTL=${TTL:=300}
JSON_sh="$(dirname "$0")/JSON.sh"

fail() {
	echo "$0: $@" >&2
	/sbin/ddns_custom_updated 0
	exit 1
}

req() {
	curl --fail --silent "$@" || \
		fail "无效请求"
}

update_record() {
	REQ="email=$EMAIL&token=$TOKEN&id=$1&data=$IP_ADDRESS&ttl=$TTL"
	req -d "$REQ" "https://i.hostker.com/api/dnsEditRecord"
}

if [ -z "$1" ]; then
	fail "已使用IP: $0"
else
	IP_ADDRESS="$1"
fi

REQ="email=$EMAIL&token=$TOKEN&domain=$DOMAIN"
JSON=$(req -d "$REQ" "https://i.hostker.com/api/dnsGetRecords")
ALL=$(echo "$JSON" | "$JSON_sh" -b -l)
LINE=$(echo "$ALL" | grep '\["records",[0-9]\+,"header"\]' | \
	grep "\"$HEADER\"")
INDEX=$(echo "$LINE" | cut -d, -f2)
ID_LINE=$(echo "$ALL" | grep "\[\"records\",$INDEX,\"id\"\]")
ID=$(echo "$ID_LINE" | cut -f2 | tr -d '"')

if [ -z ${ID} ]; then
	echo "查找ID: 失败!!"
	/sbin/ddns_custom_updated 0
	exit 1
else
	echo "查找ID: 成功! ID: ${ID}"
	update_record ${ID} &>/dev/null || \
		fail "无法更新记录"
	echo "更新成功!"
fi

/sbin/ddns_custom_updated 1
exit 0